### ISSUE TITLE
Blog post - How Long a Local Authority is required to keep records of its Financial Actions

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1073] opened 2022-03-21 16:01 UTC
The suggestion came from a user making an enquiry related to this.

Details collected from the inbox

https://mail.google.com/mail/u/0/?tab=rm&ogbl#label/Blog%2Fpublicity+ideas/FMfcgzGmtDxDGkNwVkSdwLtnwLRWHpTq

Blog or info on help page how to find this out Requires more research to complete.

>Contact the relevant local archives who might be better placed than us to advise. 
>Note section 16 of the FOI act which gives a right to advice and assistance.  One might expect a public body to set out its relevant retention and archiving policies where they relate to if information is held or not.
>Could be a blog/tweet/help page
>Publicise code of practice on records management

**Comment by sallytay** [comment] 2022-03-21 16:56
Related ticket: https://github.com/mysociety/whatdotheyknow-theme/issues/1026

**Comment by RichardTaylor** [comment] 2022-03-22 12:57
Closing as a duplicate of #1026

**Closed by RichardTaylor** 2022-03-22 12:57 UTC
Labels: blog-idea
