### ISSUE TITLE
Add advice about appealing to the First-Tier Tribunal to help pages

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#687] opened 2020-05-16 17:40 UTC
I can't see we offer any advice on how to do this.

The advice from the now defunct FOIWiki site can be found at http://web.archive.org/web/20140731031546/http://foiwiki.com/foiwiki/index.php/How_to_appeal_to_the_First-Tier_Tribunal_(Information_Rights)

I think we could do more as a site to encourage people to stand up and challenge decisions where there's good reason. This would help show there's a further option after the ICO, and would enable admins dealing with support mail to point interested users in the right direction.

**Comment by RichardTaylor** [comment] 2022-11-10 00:37
Duplicate of https://github.com/mysociety/whatdotheyknow-theme/issues/472

**Closed by RichardTaylor** 2022-11-10 00:37 UTC
Labels: help-pages
