### ISSUE TITLE
`all-authorities.csv` frequently fails to generate (504 error)

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1369] opened 2022-08-22 01:53 UTC
The CSV download at [/body/all-authorities.csv](https://www.whatdotheyknow.com/body/all-authorities.csv) frequently fails to complete successfully, returning 504 errors.

There doesn't seem to be a 'good' or 'bad' time for this, e.g. it'd perhaps be less likely to work during batch processing times - but it seems to malfunction irrespective of the time of day. I'm not sure if we're running into a capacity limit owing to the size of the authority database?

@ajparsons kindly linked me to the [processed version](https://mysociety.github.io/wdtk_authorities_list/datasets/whatdotheyknow_authorities_dataset/latest)  of the dataset recently, but that isn't showing any changes to the authority tables since `2022-07-31 04:41:22`; so I wonder if this perhaps gives us a starting point as to when the malfunction became an issue.

FWIW, I'm filing this on the whatdotheyknow-theme repo, as I suspect it is a problem unique to the UK - but it might actually be an upstream issue in Alaveteli itself.

**Comment by ajparsons** [comment] 2022-08-22 09:52
Just to say the processed version problem was unrelated - that should hopefully now continue to update but I'll monitor over the next few days https://mysociety.github.io/wdtk_authorities_list/

I get around the issue by having a long-time out and then asking the server until it eventually gives it.

**Comment by RichardTaylor** [comment] 2022-08-22 18:53
Duplicate of 

* https://github.com/mysociety/whatdotheyknow-theme/issues/1369

which itself has been closed in favour of 

https://github.com/mysociety/alaveteli/issues/3983#issuecomment-1184173465

**Closed by RichardTaylor** 2022-08-22 18:53 UTC
Labels: bug, bodies-database, enable-volunteers
