### ISSUE TITLE
Blog pages missing navigation buttons

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#600] opened 2019-08-17 17:31 UTC
> The first issue I came across was the 'blog' page where it only allows me to read the first page of posts - do we have previous blog posts or is it possibly a Dev issue which is not showing the 'next' and/or page numbers to 'go back in time' to see previous blog posts.

It's possible we've not had/used the blog that long. I don't know if it's linked with the mySociety blog or if it is separate. If it was linked I'd expect to see a lot more.

https://www.whatdotheyknow.com/blog

![image](https://user-images.githubusercontent.com/47503358/63215319-b9164400-c11c-11e9-8126-6b42b76725aa.png)

Should there be navigation buttons here?

**Comment by garethrees** [comment] 2019-08-19 08:25
Yeah, it imports a subset of mysociety.org blog posts. We've never had pagination here as far as I know, but maybe the feed used to include more items than it does now. Closing as a duplicate of https://github.com/mysociety/alaveteli/issues/3663.

**Closed by garethrees** 2019-08-19 08:25 UTC
