### ISSUE TITLE
Consider adding tables of contents to help pages

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1139] opened 2022-04-17 19:36 UTC
On some of the longer help pages, or perhaps all/most of them except the very shortest, it might be useful to insert tables of contents, to allow users to more easily navigate the page.

I'm not sure whether this would/could/should be manual or automatic, hence placing the issue here, rather than in Alaveteli (where it should presumably be if it were to be an automatic feature).  If it has to be manual, I might be able to do it myself, perhaps with a little guidance to start me off.

**Comment by mdeuk** [comment] 2022-04-18 06:46
Duplicate of #878

**Closed by mdeuk** 2022-04-18 06:46 UTC
