### ISSUE TITLE
HTTPS on the Files server results in error

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#566] opened 2019-04-09 14:56 UTC
hi

![image](https://user-images.githubusercontent.com/11923618/55810642-d63c6580-5adf-11e9-9246-f586657c1bc4.png)

That's https://files.whatdotheyknow.com/request/pre_application_advice_1700985pr/8985_Reissue_26.03.2019.zip

I have to use http://files.whatdotheyknow.com/request/pre_application_advice_1700985pr/8985_Reissue_26.03.2019.zip

The rest of WhatDoTheyKnow is SSL only. I know that FOI responses shouldn't include personal data etc. and this isn't login data etc. but still would suggest that the files server SSL should work, and also that all requests to non-encrypted HTTP should be redirected to SSL

**Comment by garethrees** [comment] 2019-04-09 15:26
Closing as a duplicate of https://github.com/mysociety/whatdotheyknow-theme/issues/349.

**Closed by garethrees** 2019-04-09 15:26 UTC

**Comment by garethrees** [comment] 2019-04-11 09:02
This has been fixed

**Comment by kingqueen3065** [comment] 2019-04-12 15:00
thank you very much @garethrees
