### ISSUE TITLE
Add impactful FOI requests to homepage

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/whatdotheyknow-theme#485] opened 2018-07-18 14:23 UTC
We show plenty of information about how the site works and is active, but we don't talk about it's impact at all.

The homepage should show some examples of where requests have had great impact.

Content is available https://2017.mysociety.org/foi/ https://www.mysociety.org/50-news-stories-uncovered-by-whatdotheyknows-users/

**Comment by garethrees** [comment] 2018-07-23 11:55
Closing as a duplicate of https://github.com/mysociety/alaveteli/issues/2812

**Closed by garethrees** 2018-07-23 11:55 UTC
Labels: t:design
