### ISSUE TITLE
Consider publishing public holiday deadline changes on ste

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#959] opened 2021-12-24 09:23 UTC
As suggest by a user

"Do you have a calculator or tool that automatically works this out?
If so, would you consider publishing this on your website? I think it would be helpful for public authorities as I’ve noticed a lot of authorities will miscalculate deadlines"

It may be useful to users as well as authorities.

**Comment by mdeuk** [comment] 2021-12-27 01:00
The Scottish Information Commissioner (OSIC) have a calculator [on their website](https://www.itspublicknowledge.info/YourRights/ResponseCalculatorInstructions.aspx), which might be helpful to look at when considering this issue.

It's worth noting - our own calculations factor the _type_ of public body information is being requested from; as some bodies, [such as schools](https://www.legislation.gov.uk/uksi/2004/3364/regulation/3/made), have differing deadlines to the standard 20 working days.

**Comment by garethrees** [comment] 2022-01-04 13:22
Closing as a duplicate of https://github.com/mysociety/alaveteli/issues/5101.

**Closed by garethrees** 2022-01-04 13:22 UTC
Labels: help-pages, user-experience
