### ISSUE TITLE
Consider adding Acer Trust (Schools) to bodies database

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1018] opened 2022-03-01 13:51 UTC
Noted on Inbox thread that Matthew Arnold School is now part of the Acer Trust, 

As detailed here https://www.maschool.org.uk/Our-School/Governance/
Truest website - AcerTrust https://acertrust.org.uk/

We currently list all the schools in the trust
Botley School https://www.whatdotheyknow.com/admin/bodies/102861
Chalgrove Community Primary School https://www.whatdotheyknow.com/admin/bodies/40172
Icknield Community College https://www.whatdotheyknow.com/admin/bodies/43878
Matthew Arnold School https://www.whatdotheyknow.com/admin/bodies/34102
Stadhampton Primary School https://www.whatdotheyknow.com/admin/bodies/101129
Watlington Primary School https://www.whatdotheyknow.com/admin/bodies/47108
Wood Green School https://www.whatdotheyknow.com/admin/bodies/46498

We don't currently list the trust itself.

Suggestion to update the notes to mention that they are all part of the Acer Trust and look at listing the trust itself.

**Comment by RichardTaylor** [comment] 2022-03-01 18:43
I think our current practice is to list individual academy schools on the site as bodies, even though the body subject to FOI is technically in many cases the [multi] academy trust they are part of. We do this as we think listing the schools is likely to best help our users, and promote the fact FOI requests can be made to the schools. 

We tend to list the [multi] academy trusts themselves only on request, we have not yet sought to list them comprehensively, I think as we expect the school listings suffice. 

We have listed many, particularly larger, academy trusts in response to requests. 

https://www.whatdotheyknow.com/body/list/academy_trust

I think we should avoid listing both the trust and the school for academy trusts which run just one school. 

I don't think we should ourselves add selected academy trusts on a piecemeal basis. 

Options:

* Carry on as we are and add academy trusts on request from users, where there is a case for doing so. 
* Proactively add, in bulk, all academy trusts responsible for more than x schools. Maybe x=3 ?

**Freedom of Information Act Link**
Bodies subject to FOI include:

>The proprietor of an Academy, in respect of information held for the purposes of the proprietor's functions under Academy arrangements.

https://www.legislation.gov.uk/ukpga/2000/36/schedule/1/paragraph/52A

**Comment by RichardTaylor** [comment] 2022-03-18 23:35
One issue caused by our current approach is that when someone makes a request to each school run by an academy trust technically the trust is receiving multiple copies of a request. 

If the request is school-specific, as it usually will be, by virtue of being addressed to a specific school, this probably isn't a problem. It may be problematic in some circumstances though.

**Comment by HelenWDTK** [comment] 2023-06-22 13:56
Closing as complete

**Closed by HelenWDTK** 2023-06-22 13:56 UTC
Labels: bodies-database, administrative-task
