### ISSUE TITLE
Caching problem, possible server/deployment issue?

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#588] opened 2019-07-30 10:26 UTC
There seems to be a caching issue on the site, it has been noted a couple of times recently

> I’m seeing a caching issue with “Peterborough Limited” in the public body search results but still Aragon...” as the name of the body on the body page. 

> I’m seeing the issue on mobile internet and wired broadband (independent companies). 

The above relate to https://www.whatdotheyknow.com/body/aragon_direct_services

Similar was also noted on the Alaveteli Slack channel on 25/07/19, in relation to a user page (96865). Admins had made some requests requester_only however they were still appearing to non-logged in users.

We'll note any further occurrences of this on the issue here.

**Comment by garethrees** [comment] 2019-07-30 10:36
From the issue description, I can't really establish what the problem is here. It would be good to add a description (ideally with screenshots) of:

* What action you're performing
* The expected results
* The actual results

Note that slow search re-indexing is a known issue (https://github.com/mysociety/alaveteli/issues/1179, https://github.com/mysociety/alaveteli/issues/4213, https://github.com/mysociety/alaveteli/issues/1168).

**Comment by MattK1234** [comment] 2019-07-30 11:01
I'll see if I can recreate it and get some screenshots. @richardtaylor noted these two examples so might be able to add some more details.

**Comment by MattK1234** [comment] 2019-07-30 11:17
> I'll see if I can recreate it

I'm unable to recreate it. I changed the name of Test Quango to Test Quango 1, then navigated to the body page via the public body search. It worked.

Perhaps it depends on browsers? I'm using Chrome on Android, in an Incognito tab.

**Comment by RichardTaylor** [comment] 2019-07-30 22:35
1. I use the admin interface to change the name of test authority body 88253
2. Straight after making the change I visit the public page for the body while logged in and the change is immediately visible. 
3. On another browser while not logged in the change is not visible 
4. Change still not visible 5 minutes after it was made. 
5. Adding ?cachebust=nksjdnmskl to the URL while not logged in does result in the new name appearing, but without the parameters the original name is still shown. 
6. On searching for "DAA" the test authority comes up with the new name in the search results, but the body page has still not updated. 
7. 20 minutes after the change was made, still no update when viewing the body page when not logged in. Confirmed via accessing the site via remote service eg. ready.mobi (not having used that service to access the page before). 
8. 30 minutes ... no change

Cache refreshing for body page is slower than expected. (Though I don't know what cache times are currently to be expected for different page types).

**Comment by garethrees** [comment] 2019-07-31 08:52
The public body page is cached for 24 hours for non-logged-in users (introduced in 2011 https://github.com/mysociety/alaveteli/commit/708f8d6277bd0f218f8b85c1cc741fa2917fcb44). We _could_ reduce it, but I think the intent was that this type of change happens fairly rarely and the benefit of reducing requests that hit the application layer outweighs the occasional slow cache refresh.

**Comment by MattK1234** [comment] 2019-08-08 13:29
We encountered what might be a caching issue again today on WhatDoTheyKnow.

**Action**
Another site administrator hid an annotation from public view (89009)
I then was looking at the same support email, and went to do the same.
I then went to the user's public page on WDTK (186805)
I also did the same as a non logged-in user.

**Expected result**
I expected to see the one hidden annotation on the user admin page.
I expected to see nothing on the public page

**Actual result**
I saw the one hidden annotation on the user admin page
_I saw the one annotation on the public page (screenshot attached)_

After approximately half an hour, I no longer saw the annotation on the user public page when logged in, but I do see it when not logged in.

The count of annotations seems to be correct, as it shouldn't include hidden annotations, albeit, in this state it could cause confusion.

Clicking the link to the request shows the request page but the annotation is correctly hidden.

![image](https://user-images.githubusercontent.com/47503358/62707155-c75fb400-b9e8-11e9-9723-dea95624c2eb.png)

**Comment by garethrees** [comment] 2019-08-08 13:33
The [user page](https://github.com/mysociety/alaveteli/blob/develop/app/controllers/user_controller.rb#L29) is also cached for 24 hours, so is currently working as intended (though ofc, perhaps this isn't ideal).

If you get the described actual result after 24 hours from hiding the comment, then there may be a bug.

**Comment by MattK1234** [comment] 2019-08-08 14:01
Thanks Gareth.

It might be worth considering whether this is something we want to change. There's often circumstances where we don't want content hanging around when we've removed/hidden it.

Perhaps an admin option to 'clear cached page' might solve this, although it'd be slightly more admin work to navigate to the user page and click it.

**Comment by garethrees** [comment] 2019-08-08 14:12
This has quite a lot of history.

We used to have [some code](https://github.com/mysociety/alaveteli/blob/5ba1c255ce3806b8f010583366185c0b76bb5829/app/models/purge_request.rb) that attempted to periodically purge the "external" Varnish cache, but it didn't work too well so got [deprecated](https://github.com/mysociety/alaveteli/pull/4252) and [removed](https://github.com/mysociety/alaveteli/commit/a28dc2d58c25a326b062bb28285bacb3ff014c76).

I think https://github.com/mysociety/alaveteli/issues/1006 is the best ticket to consider for improving the situation, so I'll close this now that its referenced there. I don't think requiring admins to _have_ to deal with cache purges is a great solution – it should be handled automatically – but there's a lot of unpicking to do before that becomes possible.

**Closed by garethrees** 2019-08-08 14:12 UTC

**Comment by RichardTaylor** [comment] 2019-08-09 17:37
On the specific instance raised here, doesn't the presence of 
>This person's 0 annotations 

indicate this isn't a whole page caching issue but perhaps another problem such as a search index issue? The page should never have said "This person's 0 annotations". 

I am sceptical that we have never had the ability to remove request titles and snippets from the web (on user/body pages) pretty promptly - I thought we could do so within 5-10 minutes, but I may be wrong.

**Comment by RichardTaylor** [comment] 2020-11-27 19:20
It's currently over 15 minutes since I made some censor rules on a request page and I'm still waiting for the cache to update.
