### ISSUE TITLE
Add a public note to bodies which have recently used Egress.com and similar to send responses

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#826] opened 2021-06-10 13:20 UTC
Relevant bodies could be identified by searching WhatDoTheyKnow.com 

A bulk update of relevant bodies could be made via a CSV upload

The public note could say something like:

>This body has previously responded to requests by providing links to Egress.com rather than simply sending the response via email. We recommend explicitly requesting a response by email, this will ensure the response is published and accessible to all on WhatDoTheyKnow.com

We could link to 

https://www.legislation.gov.uk/ukpga/2000/36/section/11
https://www.legislation.gov.uk/asp/2002/13/section/11 

which require public bodies to take account of reasonable requests as to the means of communication of a response. 
 
Similar notes could be placed on bodies which have a habit of responding via links to a new entry on their disclosure log. 

We might want to also note that responses on other websites can be obtained and uploaded to WhatDoTheyKnow, if the admin team are sent a copy, or a link. 

Ideally we'd have tag based notes: https://github.com/mysociety/alaveteli/issues/387

See also:
* https://github.com/mysociety/alaveteli/issues/6305 Add additional material to the standard request template on a per body basis based on tags

* https://github.com/mysociety/alaveteli/issues/6304  Offer advice if egress, or other similar services, are mentioned in a response

**Comment by RichardTaylor** [comment] 2021-06-10 13:24
>A bulk update of relevant bodies could be made via a CSV upload

Or an update to a handful of larger offending bodies / major offenders could be done manually. 

A search of the support mailbox might identify those bodies particularly causing us, and our users, a problem.

**Comment by mdeuk** [comment] 2021-06-10 17:39
If we're doing this for Egress, it'd be good if we could genericise the text slightly - for example, we've:

- the constant annoyance of the University of Southampton which goes to great effort to avoid actually sending a substantive reply via WDTK (the most recent favoured example being uploading files on their own website, prior being a file download repository and encrypted PDFs)
- Network Rail who use OneDrive to send larger files but then require users to supply a 'one time passcode' which changes each time the link is clicked (meaning request threads get clogged with loads of OTP emails!)
- Waltham Forest and the persistent 'broken links' (caused by linking files from an Amazon S3 bucket which contain spaces in the filename)
- other bodies that reply with file sharing services such as Dropbox, WeTransfer, and (perhaps) Google Drive.

A starter for ten could be indicating that we're aware that "this public body sometimes replies to requests either in an encrypted format, or with a link to data elsewhere"… followed by the text proposed.

For bodies that have replied using a link to data elsewhere, it'd be a good idea if we could capture these so that we can upload to the file server - and perhaps evangelise with FOI officers on how they can use our own upload capability to save inconvenience for everyone.

**Comment by HelenWDTK** [comment] 2023-06-20 08:55
I think we cover this with `response_link` - closing as complete

**Closed by HelenWDTK** 2023-06-20 08:55 UTC
Labels: non-developer
