### ISSUE TITLE
TOTP 2FA.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mysociety/whatdotheyknow-theme#1898] opened 2024-07-19 23:53 UTC
Currently, https://www.whatdotheyknow.com/profile/two_factor provides similar functionality. This isn't of significant use, when TOTP provides this in a more standardized (and generally superior) manner.

**Comment by WilliamWDTK** [comment] 2024-07-20 13:19
I think this would be better in the repo for the software WDTK runs on (Alaveteli: [mysociety/alaveteli](https://github.com/mysociety/alaveteli)), since it would probably be implemented there, and it is possibly a duplicate of https://github.com/mysociety/alaveteli/issues/4093. If you don't think that sufficiently represents your issue, you might wish to open a new issue there, ensuring you describe the problem in sufficient detail (e.g. would this be for all log-ins, or only for password resets as is currently done, would it be opt-in, etc).

Also see:
- https://github.com/mysociety/alaveteli/issues/6916
- https://github.com/mysociety/alaveteli/issues/4093

**Closed by WilliamWDTK** 2024-07-20 13:19 UTC
