### ISSUE TITLE
Use of @extend for buttons

### ISSUE THREAD

**Issue by dracos** [mysociety/whatdotheyknow-theme#415] opened 2017-08-25 09:29 UTC
`responsive/custom.scss` uses a fair number of `@extend`s which could probably be better structured. As an example, `button-secondary` is used (at its core, all but one style removed) as follows below.

Some reading:
https://www.sitepoint.com/avoid-sass-extend/
https://csswizardry.com/2014/11/when-to-use-extend-when-to-use-a-mixin/
http://pressupinc.com/blog/2014/11/dont-overextend-yourself-in-sass/
https://www.smashingmagazine.com/2015/05/extending-in-sass-without-mess/

```
a.button-secondary, .button-secondary, .button-secondary:visited {
    &:hover, &:active, &:focus {
        color: #333;
    }
}

.request-header__action-bar {
  .action-menu__button {
    @extend .button-secondary;
  }
}

.request-footer__action-bar__actions {
  .action-menu__button {
    @extend .button-secondary;
  }
}

.authority__header__action-bar {
  .action-bar__follow-button, .feed_link_sidebar {
    .link_button_green {
      @extend .button-secondary;
    }
  }

  .authority__body__sidebar .list-filter-item input[type=submit] {
    @extend .button-secondary;
  }
}

#header_right, #right_column {
  a[href$="/report/new"] {
    @extend .button-secondary;
  }
}

div.pagination span.current, div.pagination a, div.pagination a:visited, .pagination .previous_page, .pagination .next_page, .pagination .current {
  @extend .button-secondary;
}
```

Which compiles to:
```
a.button-secondary:hover, .request-header__action-bar a.action-menu__button:hover,
.request-footer__action-bar__actions a.action-menu__button:hover,
.authority__header__action-bar .action-bar__follow-button a.link_button_green:hover, .authority__header__action-bar .feed_link_sidebar a.link_button_green:hover,
#header_right a[href$="/report/new"]:hover,
#right_column a[href$="/report/new"]:hover, div.pagination a:hover,
.pagination a.previous_page:hover, .pagination a.next_page:hover, .pagination a.current:hover,
a.button-secondary:active, .request-header__action-bar a.action-menu__button:active,
.request-footer__action-bar__actions a.action-menu__button:active,
.authority__header__action-bar .action-bar__follow-button a.link_button_green:active,
.authority__header__action-bar .feed_link_sidebar a.link_button_green:active,
#header_right a[href$="/report/new"]:active, #right_column a[href$="/report/new"]:active,
div.pagination a:active, .pagination a.previous_page:active, .pagination a.next_page:active,
.pagination a.current:active, a.button-secondary:focus, .request-header__action-bar a.action-menu__button:focus,
.request-footer__action-bar__actions a.action-menu__button:focus,
.authority__header__action-bar .action-bar__follow-button a.link_button_green:focus,
.authority__header__action-bar .feed_link_sidebar a.link_button_green:focus,
#header_right a[href$="/report/new"]:focus, #right_column a[href$="/report/new"]:focus,
div.pagination a:focus, .pagination a.previous_page:focus, .pagination a.next_page:focus,
.pagination a.current:focus, .button-secondary:hover, .request-header__action-bar .action-menu__button:hover,
.request-footer__action-bar__actions .action-menu__button:hover,
.authority__header__action-bar .action-bar__follow-button .link_button_green:hover,
.authority__header__action-bar .feed_link_sidebar .link_button_green:hover,
.authority__header__action-bar .authority__body__sidebar .list-filter-item input[type=submit]:hover,
#header_right a[href$="/report/new"]:hover, #right_column a[href$="/report/new"]:hover,
div.pagination a:hover, .pagination .previous_page:hover, .pagination .next_page:hover, .pagination .current:hover,
.button-secondary:active, .request-header__action-bar .action-menu__button:active,
.request-footer__action-bar__actions .action-menu__button:active, .authority__header__action-bar .action-bar__follow-button .link_button_green:active,
.authority__header__action-bar .feed_link_sidebar .link_button_green:active,
.authority__header__action-bar .authority__body__sidebar .list-filter-item input[type=submit]:active,
#header_right a[href$="/report/new"]:active, #right_column a[href$="/report/new"]:active,
div.pagination a:active, .pagination .previous_page:active, .pagination .next_page:active, .pagination .current:active,
.button-secondary:focus, .request-header__action-bar .action-menu__button:focus,
.request-footer__action-bar__actions .action-menu__button:focus,
.authority__header__action-bar .action-bar__follow-button .link_button_green:focus,
.authority__header__action-bar .feed_link_sidebar .link_button_green:focus,
.authority__header__action-bar .authority__body__sidebar .list-filter-item input[type=submit]:focus,
#header_right a[href$="/report/new"]:focus, #right_column a[href$="/report/new"]:focus,
div.pagination a:focus, .pagination .previous_page:focus, .pagination .next_page:focus, .pagination .current:focus,
.button-secondary:visited:hover, .request-header__action-bar .action-menu__button:visited:hover,
.request-footer__action-bar__actions .action-menu__button:visited:hover,
.authority__header__action-bar .action-bar__follow-button .link_button_green:visited:hover,
.authority__header__action-bar .feed_link_sidebar .link_button_green:visited:hover,
.authority__header__action-bar .authority__body__sidebar .list-filter-item input[type=submit]:visited:hover,
#header_right a[href$="/report/new"]:visited:hover, #right_column a[href$="/report/new"]:visited:hover,
div.pagination a:visited:hover, .pagination .previous_page:visited:hover, .pagination .next_page:visited:hover,
.pagination .current:visited:hover, .button-secondary:visited:active, .request-header__action-bar .action-menu__button:visited:active,
.request-footer__action-bar__actions .action-menu__button:visited:active,
.authority__header__action-bar .action-bar__follow-button .link_button_green:visited:active,
.authority__header__action-bar .feed_link_sidebar .link_button_green:visited:active,
.authority__header__action-bar .authority__body__sidebar .list-filter-item input[type=submit]:visited:active,
#header_right a[href$="/report/new"]:visited:active,
#right_column a[href$="/report/new"]:visited:active,
div.pagination a:visited:active, .pagination .previous_page:visited:active, .pagination .next_page:visited:active,
.pagination .current:visited:active, .button-secondary:visited:focus, .request-header__action-bar .action-menu__button:visited:focus,
.request-footer__action-bar__actions .action-menu__button:visited:focus,
.authority__header__action-bar .action-bar__follow-button .link_button_green:visited:focus,
.authority__header__action-bar .feed_link_sidebar .link_button_green:visited:focus,
.authority__header__action-bar .authority__body__sidebar .list-filter-item input[type=submit]:visited:focus,
#header_right a[href$="/report/new"]:visited:focus, #right_column a[href$="/report/new"]:visited:focus,
div.pagination a:visited:focus, .pagination .previous_page:visited:focus,
.pagination .next_page:visited:focus, .pagination .current:visited:focus {
    color: #333; }
```

**Comment by garethrees** [comment] 2017-11-06 17:11
Related to https://github.com/mysociety/alaveteli/issues/3845

**Comment by garethrees** [comment] 2017-11-14 09:37
Going to close this as effectively a duplicate of https://github.com/mysociety/alaveteli/issues/3845.

**Closed by garethrees** 2017-11-14 09:37 UTC
Labels: 0 - backlog, design
